/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  "getting-started": [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    }
  ],
  "main": [
    {
      type: 'autogenerated',
      dirName: 'main',
    }, {
      type: 'html',
      value: '<hr role="separator" aria-orientation="horizontal" class="sidebar-hr">', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    }, {
      type: 'link',
      label: '🌐 ArmSoM Offical Website', // The link label
      href: 'https://armsom.org', // The external URL
    },{
      type: 'link',
      label: '💬 ArmSoM Forum', // The link label
      href: 'https://forum.armsom.org', // The external URL
    }, {
      type: 'link',
      label: '💭 ArmSoM Discord', // The link label
      href: 'https://discord.com/invite/THfTEatpfK', // The external URL
    }, {
      type: 'html',
      value: '<hr role="separator" aria-orientation="horizontal" class="sidebar-hr">', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },  {
      type: 'html',
      value: 'follow us', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },{
      type: 'link',
      label: 'Youtube', // The link label
      href: 'https://www.youtube.com/@ArmSoM', // The external URL
    },{
      type: 'link',
      label: 'Twitter', // The link label
      href: 'https://twitter.com/Armsom_official', // The external URL
    },{
      type: 'link',
      label: 'bilibili', // The link label
      href: 'https://forum.armsom.org', // The external URL
    }
  ],
  "general-tutorial": [
    {
      type: 'category',
      label:  "General tutorial" ,
      link: {
        type: 'generated-index',
        title: 'General tutorial',
        description: 'ArmSoM General Tutorial, Applicable to All ArmSoM Products',
        slug: '/general-tutorial',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'general-tutorial',
      }],
      // items: ['general-tutorial/baidu-cloud'],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
