/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  "main": [
    {
      type: 'autogenerated',
      dirName: 'main',
    }, {
      type: 'html',
      value: '<hr role="separator" aria-orientation="horizontal" class="sidebar-hr">', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    }, {
      type: 'link',
      label: '🌐 Offical Website', // The link label
      href: 'https://armsom.org', // The external URL
    },{
      type: 'link',
      label: '💬 Forum', // The link label
      href: 'https://forum.armsom.org', // The external URL
    }, {
      type: 'link',
      label: '💭 Discord', // The link label
      href: 'https://discord.com/invite/THfTEatpfK', // The external URL
    }, {
      type: 'html',
      value: '<hr role="separator" aria-orientation="horizontal" class="sidebar-hr">', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },  {
      type: 'html',
      value: 'Follow us', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },{
      type: 'link',
      label: 'Twitter', // The link label
      href: 'https://twitter.com/Armsom_official', // The external URL
    },{
      type: 'link',
      label: 'Mastodon', // The link label
      href: 'https://mastodon.social/@armsom_jackson', // The external URL
    },{
      type: 'link',
      label: 'bilibili', // The link label
      href: 'https://space.bilibili.com/101696800', // The external URL
    },
  ],
};

module.exports = sidebars;
